### ISSUE TITLE
define Duration object 

### ISSUE THREAD

**Issue by natasha-aleksandrova** [googleapis/python-security-private-ca#17]
https://googleapis.dev/python/privateca/latest/privateca_v1beta1/types.html

your documentation references Duration object but I'm not finding reference to it in the doc, can you please point to the doc for that class?

**Comment by busunkim96** [comment]
Hi @natasha-aleksandrova,

The 'Duration' comes from the `protobuf` package. https://googleapis.dev/python/protobuf/latest/google/protobuf/duration_pb2.html

Since this library uses proto-plus as a wrapper, you should be able to write fields that expect `Duration` with `datetime.timedelta` objects. https://proto-plus-python.readthedocs.io/en/latest/marshal.html#well-known-types

**Comment by natasha-aleksandrova** [comment]
thank you, this addresses my question -- it would be nice if this was included in the ca dogs 🙂

**Comment by busunkim96** [comment]
Yep, sorry about the poor type identification in the docs. #13 should make it a bit better.

**Comment by natasha-aleksandrova** [comment]
that's great to hear 👍
